---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spring-boot-docker
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: spring-boot-docker
          servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-docker
  name: spring-boot-docker
spec:
  ports:
    - port: 8080
  selector:
    app: spring-boot-docker

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-docker
    spec:
      containers:
      - name: spring-boot-docker
        image: itstarting/spring-boot-docker
        ports:
        - containerPort: 8080